### ISSUE TITLE
If the first block on a page is h2, it has extra padding/margin between header and h2

### ISSUE THREAD

**Issue by superkumario64** [ucsc/ucsc-2022#121]
We noticed this when working on: https://diplomas.ucsc.edu/

**Comment by knice** [comment]
@superkumario64 I created a composite image below that shows the distance between the yellow line and the first block holds steady at ~158px no matter which block is there. The reason that gap is so big is because the site doesn't have a main navigation block, and template parts have a fixed bottom margin across the theme. So the space left empty by the missing nav block **+** the standard margin on the bottom of the header part creates a large gap.

It will be rare for a site to not have a main navigation block, so I'm going to close this. If we run into this situation again, we'll open a new ticket and see about making a change.

![headers-no-nav](https://user-images.githubusercontent.com/36719/189203217-d21c53f6-55ed-4c9d-b85b-dc2f1f803296.png)

**Comment by superkumario64** [comment]
Make sense, thank you for the explanation.
