### ISSUE TITLE
Last Modified Date

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#160]
From Becca: "One of the useful features on ucsc.edu and other sites is the "Last modified date" in the footer.  
How can a "Last Modified date" be added to the footers in Campus Wordpress?  
I tried to see if there was some shortcode or another way - a lot of the items online are plugins for Wordpress."

**Comment by kanarb** [comment]
Thanks Jason. Yes, please add this back to the footer.

**Comment by knice** [comment]
[Here is the last commit](https://github.com/ucsc/ucsc-2022/commit/afd67dfb6944fd9b735b3bdda8b1263e15ddfd53#diff-af1c5e70000f79ec3eedc7905fd4ce902acccf21e92c524b4b81c4233f4fca37) where we had it working as we wanted it.

**Comment by knice** [comment]
![screenshot-2022-12-01-133821](https://user-images.githubusercontent.com/36719/205133550-8dc720fb-a1bc-4092-a350-40b53b974492.jpg)

![screenshot-2022-12-01-133919](https://user-images.githubusercontent.com/36719/205133717-debcfc15-327a-410a-9dd4-c88270fdd3fe.jpg)

**Comment by Herm71** [comment]
@knice, in the _Last modified:_ paragraph sidebar settings, under **Dimensions>Margin>Top** what dimensions are you using for the "1" `px,  em, rem`?

**Comment by Herm71** [comment]
@knice Nevermind, I figured it out

**Comment by knice** [comment]
Should be 1rem?

**Comment by Herm71** [comment]
@knice I'm preparing to push this up and issue a PR but before I do, here are some screenshots of my environment for comparison's sake. (BTW, the reason the shortcode worked when we tested it in your `local-dev` is because we moved it to the [custom functionality plugin](https://github.com/ucsc/ucsc-custom-functionality/blob/main/lib/functions/shortcodes.php). No additional work is needed there.) 

Editor settings:
![last-modified-editor](https://user-images.githubusercontent.com/1000543/205180181-dd77e7b8-d900-43bb-838a-b49444de69ed.png)

 Front-end:
![last-modified-front](https://user-images.githubusercontent.com/1000543/205180258-6841555d-2af6-4e0b-bb5d-7265291d1dc2.png)

**Comment by knice** [comment]
That looks good. We might need to adjust the font-weight, but let's go with that you have there for now. 👍

**Comment by knice** [comment]
@Herm71 possible to add this _after_ the global footer, so it looks similar to the way [we had it configured here](https://github.com/ucsc/ucsc-2022/issues/160#issuecomment-1334189529)? 

We add the global footer in functions.php. Maybe we can add the global footer, and then add another horizontal row with blue background (so it looks like it comes with the global footer) that contains the shortcode for last-modifed?

**Comment by Herm71** [comment]
Here's what it looks like so far:

Desktop:
![lm-desktop](https://github.com/ucsc/ucsc-2022/assets/1000543/0ee0c0a3-5465-435d-bd99-e434c47b4071)

Mobile:
![lm-mobile](https://github.com/ucsc/ucsc-2022/assets/1000543/2dae5176-4431-4ce3-840f-bd0a7c16d093)
