### ISSUE TITLE
Homepage content overflow

### ISSUE THREAD

**Issue by Yingkit22** [ucsc/ucsc-2022#161]
Content overflows on homepage. See https://csl-careers.wordpress.ucsc.edu/

On site: 
<img width="2304" alt="Screen Shot 2022-11-30 at 12 28 29 PM" src="https://user-images.githubusercontent.com/103080126/204901407-aa330fde-e5a8-498c-ba36-ee5ca792008c.png">

However, looks fine on editor:
<img width="2304" alt="Screen Shot 2022-11-30 at 12 29 16 PM" src="https://user-images.githubusercontent.com/103080126/204901547-5a753c3c-5803-4e6c-8598-bd14c08538df.png">

**Comment by knice** [comment]
I moved the content in question to the [home page *page*](https://csl-careers.wordpress.ucsc.edu/) (instead of the front page template in the appearance editor), and wrapped it in a _group_ block. A group block is typically what you use to constrain the width of a other blocks so they don't extend to the full width of the page. Setting the width of the group block to "none" fixed the problem.

**Comment by knice** [comment]
![screenshot-2022-11-30-161038](https://user-images.githubusercontent.com/36719/204908747-d080a46c-f962-4e0b-a203-81dcfcf744d3.jpg)
