### ISSUE TITLE
Phantom Menu in footer?

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-2022#41]
![phantom menu](https://user-images.githubusercontent.com/7795841/167185918-d4188b0a-9124-45b9-bb2f-bb4c55287266.jpg)
This site was built before the new menu block editor. There is an old menu hanging out in my footer that I can't get rid of or even find anymore.
Thoughts?

**Comment by knice** [comment]
That menu was in the `footer-site` template part. Because the links are colored white, it looked like that template part was empty. I removed the content from that template part and the region is now empty. You can [edit your site and update the content of that region](https://websites.wordpress.ucsc.edu/wp-admin/themes.php?page=gutenberg-edit-site&postType=page&postId=474).
